### ISSUE TITLE
Error On App install

### ISSUE THREAD

**Issue by thegitprince** [alyf-de/frappe_qr_demo#1]
Installed the app on my v15 instance causing an error with the message:
 "FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/dist/js/build_events.bundle.YS7XLMHO.js'"
 similar messages for other missing assets js files are also showing. The error is displayed on all pages on refresh.
 
 After the same, tried uninstalling and removing the app, but the error persists in my instance.
 
 
![image](https://github.com/user-attachments/assets/9f17e021-4519-44e3-b060-d8715cca542f)

Detailed error message below:
====================
### App Versions
```
{
	"erpnext": "14.65.4",
	"frappe": "14.68.0",
	"hrms": "14.24.0",
	"payments": "0.0.1"
}
```
### Route
```
Workspaces/Home
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1611, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/client.py", line 351, in get_js
    with open(contentpath) as srcfile:
FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/dist/js/onboarding_tours.bundle.DLMLTCOE.js'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"items": "[\"/assets/frappe/dist/js/onboarding_tours.bundle.DLMLTCOE.js\"]"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.get_js"
}
```
### Response Data
```
{
	"exception": "FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/dist/js/onboarding_tours.bundle.DLMLTCOE.js'"
}
```

**Comment by barredterra** [comment]
This app currently supports v14 only. Also, the error messages you posted don't appear to be related to this app.

**Comment by thegitprince** [comment]
Thanks for the reply.
About the error, I also thought the same, but strange that it appeared after the app installation and persists even after its removal. I'll find a way around it, again thanks for your time
